//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHubExplorer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitHubExplorer.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for any Github user eg..
        /// </summary>
        internal static string HomePage_InitiailSearchString {
            get {
                return ResourceManager.GetString("HomePage_InitiailSearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results matched the username: &quot;{0}&quot;, Try something like: .
        /// </summary>
        internal static string HomePage_ResultNotFoundString {
            get {
                return ResourceManager.GetString("HomePage_ResultNotFoundString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for user {0} ....
        /// </summary>
        internal static string HomePage_SearchInProgressString {
            get {
                return ResourceManager.GetString("HomePage_SearchInProgressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repositories found for user: &quot;{0}&quot;.
        /// </summary>
        internal static string RepoPage_ResultNotFoundString {
            get {
                return ResourceManager.GetString("RepoPage_ResultNotFoundString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for repositories for user: &quot;{0}&quot;.
        /// </summary>
        internal static string RepoPage_SearchInProgressString {
            get {
                return ResourceManager.GetString("RepoPage_SearchInProgressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sthewissen.
        /// </summary>
        internal static string Sample_User {
            get {
                return ResourceManager.GetString("Sample_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
